// <auto-generated />
using System;
using KosnicaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KosnicaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KosnicaApi.Models.Apiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Apiaries");
                });

            modelBuilder.Entity("KosnicaApi.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HiveId")
                        .HasColumnType("integer");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("YieldRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.HasIndex("InterventionId");

                    b.HasIndex("YieldRecordId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("KosnicaApi.Models.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<string>("ColonyStrength")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumberOfSupers")
                        .HasColumnType("integer");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<string>("QueenStatus")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.ToTable("Hives");
                });

            modelBuilder.Entity("KosnicaApi.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("KosnicaApi.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("KosnicaApi.Models.ShipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("KosnicaApi.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BeeReaction")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HiveId")
                        .HasColumnType("integer");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("integer");

                    b.Property<string>("Losses")
                        .HasColumnType("text");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HiveId");

                    b.HasIndex("InterventionId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("KosnicaApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KosnicaApi.Models.YieldRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HiveId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("WeatherConditions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("HiveId");

                    b.ToTable("YieldRecords");
                });

            modelBuilder.Entity("KosnicaApi.Models.Apiary", b =>
                {
                    b.HasOne("KosnicaApi.Models.User", "User")
                        .WithMany("Apiaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KosnicaApi.Models.Attachment", b =>
                {
                    b.HasOne("KosnicaApi.Models.Apiary", "Apiary")
                        .WithMany()
                        .HasForeignKey("ApiaryId");

                    b.HasOne("KosnicaApi.Models.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("HiveId");

                    b.HasOne("KosnicaApi.Models.Intervention", "Intervention")
                        .WithMany()
                        .HasForeignKey("InterventionId");

                    b.HasOne("KosnicaApi.Models.YieldRecord", "YieldRecord")
                        .WithMany()
                        .HasForeignKey("YieldRecordId");

                    b.Navigation("Apiary");

                    b.Navigation("Hive");

                    b.Navigation("Intervention");

                    b.Navigation("YieldRecord");
                });

            modelBuilder.Entity("KosnicaApi.Models.Hive", b =>
                {
                    b.HasOne("KosnicaApi.Models.Apiary", "Apiary")
                        .WithMany("Hives")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");
                });

            modelBuilder.Entity("KosnicaApi.Models.Intervention", b =>
                {
                    b.HasOne("KosnicaApi.Models.Apiary", "Apiary")
                        .WithMany()
                        .HasForeignKey("ApiaryId");

                    b.HasOne("KosnicaApi.Models.Hive", "Hive")
                        .WithMany("Interventions")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Apiary");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("KosnicaApi.Models.Shipment", b =>
                {
                    b.HasOne("KosnicaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KosnicaApi.Models.ShipmentItem", b =>
                {
                    b.HasOne("KosnicaApi.Models.Shipment", "Shipment")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("KosnicaApi.Models.Treatment", b =>
                {
                    b.HasOne("KosnicaApi.Models.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KosnicaApi.Models.Intervention", "Intervention")
                        .WithMany("Treatments")
                        .HasForeignKey("InterventionId");

                    b.Navigation("Hive");

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("KosnicaApi.Models.User", b =>
                {
                    b.HasOne("KosnicaApi.Models.User", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("KosnicaApi.Models.YieldRecord", b =>
                {
                    b.HasOne("KosnicaApi.Models.Apiary", "Apiary")
                        .WithMany()
                        .HasForeignKey("ApiaryId");

                    b.HasOne("KosnicaApi.Models.Hive", "Hive")
                        .WithMany("Yields")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Apiary");

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("KosnicaApi.Models.Apiary", b =>
                {
                    b.Navigation("Hives");
                });

            modelBuilder.Entity("KosnicaApi.Models.Hive", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Yields");
                });

            modelBuilder.Entity("KosnicaApi.Models.Intervention", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("KosnicaApi.Models.Shipment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KosnicaApi.Models.User", b =>
                {
                    b.Navigation("Apiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
